In [ ]:
#Begin!

# Masters' in Applied Artificial Intelligence
## Machine Learning Algorithms Course

Notebooks for the MLA course

by [*lufer*](mailto:lufer@ipca.pt)

---

# ML Modelling - Appendice - Work with Datatset
\
**Contents**:

1.  **Join Datasets**

# 1 - More about Datasets

## 1.1 - Prepare the Environment

**Importing necessary Libraries**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
import datetime
print(f"Last updated: {datetime.datetime.now()}")

Last updated: 2024-03-02 12:46:07.292622

In [85]:
#Auxiliar function
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)

    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

**Mounting Drive**

In [3]:

from google.colab import drive

# it will ask for your google drive credentiaals
drive.mount('/content/gDrive/', force_remount=True)

Mounted at /content/gDrive/

## 1.2 - *Concatenating* Datasets

Just combine data, ie, more columns or raws!

In [ ]:
dt_account= pd.read_csv("/content/gDrive/MyDrive/MIA/ColabNotebooks/Datasets/Country/account.csv", sep = ';')
#dt=dt.reset_index(drop=True)
dt_account

In [20]:
#remove column date...it is not used
dt_account = dt_account.drop("date",axis=1)

In [26]:
dt_client= pd.read_csv("/content/gDrive/MyDrive/MIA/ColabNotebooks/Datasets/Country/client.csv", sep = ';')
#dt=dt.reset_index(drop=True)
dt_client.shape

(5369, 3)

### 1.2.3 - by Rows

In [ ]:
#join account data (district_id) with client data (district_id)
#see https://geekpython.in/multiple-datasets-integration-using-pandas
# combined along the row axis by default (axis=0)
# outer join by default - joins the data exactly as it is
# "inner", data that does not match another dataset is removed
df_outer = pd.concat([dt_account,dt_client],ignore_index=True)  #ignore_index=True create a new index!
df_outer

In [ ]:
#find rows with NaN values
nan_rows = df_outer.isna().any(axis=1)
print(nan_rows)

In [ ]:

df_inner = pd.concat([dt_account,dt_client],ignore_index=True, join="inner")  #ignore_index=True create a new index!
df_inner

In [ ]:
#create a multi-level index
keys = pd.concat([dt_account,dt_client], keys=["Dataset1", "Dataset2"], join="inner")
keys

### 1.2.4 - by Columns

In [ ]:
combine_vertically = pd.concat([dt_account,dt_client], axis=1)
combine_vertically

## 1.2 - Merging Datasets

Combining datasets that have common data!

\
The `pandas.merge()` function merges data from one or more datasets based on common columns or indices.

Types of merge:
- `inner`: Default. It only includes the values that match from both datasets.

- `outer`: It includes all of the values from both datasets but fills the missing values with NaN (Not a Number).

- `left`: It includes all of the values from the left dataset and replaces any missing values in the right dataset with NaN.

- `right`: It includes all of the values from the right dataset and replaces any missing values in the left dataset with NaN.

- `cross`: It creates the Cartesian product which means that the number of rows created will be equal to the product of the row counts of both datasets. If both datasets have four rows, then four times four (4 * 4) equals sixteen (16) rows.

In [39]:
dt_account.columns

Index(['account_id', 'district_id', 'frequency'], dtype='object')

In [37]:
dt_client.columns

Index(['client_id', 'birth_number', 'district_id'], dtype='object')

### 1.2.2 - Inner

**One-to-one joins**

In [79]:
#lets merge by "district_i"
inner_merging = pd.merge(dt_account, dt_client, how="inner")  #inner by default
inner_merging.columns

Index(['account_id', 'district_id', 'frequency', 'client_id', 'birth_number'], dtype='object')

In [86]:
#inner_merging
display('dt_account', 'dt_client', 'pd.merge(dt_account, dt_client)')

dt_account
      account_id  district_id         frequency
0            576           55  POPLATEK MESICNE
1           3818           74  POPLATEK MESICNE
2            704           55  POPLATEK MESICNE
3           2378           16  POPLATEK MESICNE
4           2632           24  POPLATEK MESICNE
...          ...          ...               ...
4495         124           55  POPLATEK MESICNE
4496        3958           59  POPLATEK MESICNE
4497         777           30  POPLATEK MESICNE
4498        1573           63  POPLATEK MESICNE
4499        3276            1  POPLATEK MESICNE

[4500 rows x 3 columns]

dt_client
      client_id  birth_number  district_id
0             1        706213           18
1             2        450204            1
2             3        406009            1
3             4        561201            5
4             5        605703            5
...         ...           ...          ...
5364      13955        456030            1
5365      13956        430406            1
5366      13968        680413           61
5367      13971        626019           67
5368      13998        535812           74

[5369 rows x 3 columns]

pd.merge(dt_account, dt_client)
        account_id  district_id         frequency  client_id  birth_number
0              576           55  POPLATEK MESICNE        118        220719
1              576           55  POPLATEK MESICNE        119        225228
2              576           55  POPLATEK MESICNE        136        215126
3              576           55  POPLATEK MESICNE        145        780214
4              576           55  POPLATEK MESICNE        149        480627
...            ...          ...               ...        ...           ...
648556        2152           22  POPLATEK MESICNE       4766        670527
648557        2152           22  POPLATEK MESICNE       4769        235123
648558        2152           22  POPLATEK MESICNE       4770        241213
648559        2152           22  POPLATEK MESICNE      12468        690704
648560        2152           22  POPLATEK MESICNE      12756        495121

[648561 rows x 5 columns]

In [ ]:
#Check if there are NaN values
inner_merging.isna().sum()

In [ ]:
# selecting rows based on condition
rslt_df = inner_merging[inner_merging['account_id']==576]
rslt_df

In [ ]:
#find all NaN values
nan_df = inner_merging.isna()
print(nan_df)

In [ ]:
#find rows with NaN values
nan_rows = inner_merging.isna().any(axis=1)
print(nan_rows)

### 1.2.3 - Outer

In [60]:
outer_merging = pd.merge(dt_account, dt_client, how="outer")
outer_merging

        account_id  district_id         frequency  client_id  birth_number
0              576           55  POPLATEK MESICNE        118        220719
1              576           55  POPLATEK MESICNE        119        225228
2              576           55  POPLATEK MESICNE        136        215126
3              576           55  POPLATEK MESICNE        145        780214
4              576           55  POPLATEK MESICNE        149        480627
...            ...          ...               ...        ...           ...
648556        2152           22  POPLATEK MESICNE       4766        670527
648557        2152           22  POPLATEK MESICNE       4769        235123
648558        2152           22  POPLATEK MESICNE       4770        241213
648559        2152           22  POPLATEK MESICNE      12468        690704
648560        2152           22  POPLATEK MESICNE      12756        495121

[648561 rows x 5 columns]

### Left

In [61]:
left_merging = pd.merge(dt_account, dt_client, how="left")
left_merging

        account_id  district_id         frequency  client_id  birth_number
0              576           55  POPLATEK MESICNE        118        220719
1              576           55  POPLATEK MESICNE        119        225228
2              576           55  POPLATEK MESICNE        136        215126
3              576           55  POPLATEK MESICNE        145        780214
4              576           55  POPLATEK MESICNE        149        480627
...            ...          ...               ...        ...           ...
648556        3276            1  POPLATEK MESICNE      13548        760318
648557        3276            1  POPLATEK MESICNE      13694        765120
648558        3276            1  POPLATEK MESICNE      13803        471114
648559        3276            1  POPLATEK MESICNE      13955        456030
648560        3276            1  POPLATEK MESICNE      13956        430406

[648561 rows x 5 columns]

### Merging Datasets on the Same Column

In [63]:
# the non-matching values were removed.
merging_on_same_column = pd.merge(dt_account, dt_client, on='district_id')
merging_on_same_column

        account_id  district_id         frequency  client_id  birth_number
0              576           55  POPLATEK MESICNE        118        220719
1              576           55  POPLATEK MESICNE        119        225228
2              576           55  POPLATEK MESICNE        136        215126
3              576           55  POPLATEK MESICNE        145        780214
4              576           55  POPLATEK MESICNE        149        480627
...            ...          ...               ...        ...           ...
648556        2152           22  POPLATEK MESICNE       4766        670527
648557        2152           22  POPLATEK MESICNE       4769        235123
648558        2152           22  POPLATEK MESICNE       4770        241213
648559        2152           22  POPLATEK MESICNE      12468        690704
648560        2152           22  POPLATEK MESICNE      12756        495121

[648561 rows x 5 columns]

### Merging Datasets on Different Columns

In [64]:
left_right_merging = pd.merge(dt_account, dt_client, left_on="district_id", right_on='district_id')

### Changing the Suffix of the Column

In [65]:
chg_suffix = pd.merge(dt_account, dt_client, suffixes=["_1", "_2"], left_on="district_id", right_on='district_id')
chg_suffix

        account_id  district_id         frequency  client_id  birth_number
0              576           55  POPLATEK MESICNE        118        220719
1              576           55  POPLATEK MESICNE        119        225228
2              576           55  POPLATEK MESICNE        136        215126
3              576           55  POPLATEK MESICNE        145        780214
4              576           55  POPLATEK MESICNE        149        480627
...            ...          ...               ...        ...           ...
648556        2152           22  POPLATEK MESICNE       4766        670527
648557        2152           22  POPLATEK MESICNE       4769        235123
648558        2152           22  POPLATEK MESICNE       4770        241213
648559        2152           22  POPLATEK MESICNE      12468        690704
648560        2152           22  POPLATEK MESICNE      12756        495121

[648561 rows x 5 columns]

## 1.2 - Joining Datasets Using join()

The `join()` method works on the DataFrame object and joins the columns based on the index values.

\
The join() method, like the merge() function, includes `how` and `on` parameters.

- `how`: Default value is left join. It is the same as the how parameter of the merge() function, but the difference is that it performs index-based joins.
- `on`: A column or index name is required to join on the index in the specified dataset.
- `lsuffix` and `rsuffix`: Used to append the suffix to the left and right datasets’ overlapping columns.

In [ ]:
dt_account.join(dt_client, lsuffix="_1", rsuffix="_2").head(10)

In [ ]:
dt_client.head(13)

In [ ]:
dt_account.head(6)

### Left Join on an Index

In [ ]:
dt_account.join(dt_client.set_index("district_id"), on="district_id", how="left")
#-------------------------OR----------------------#
dt_account.join(dt_client.set_index("district_id"), on="district_id")

### Right join on an index

In [75]:
dt_account.join(dt_client.set_index("district_id"), on="district_id", how="right")

      account_id  district_id         frequency  client_id  birth_number
348        10973           18    POPLATEK TYDNE          1        706213
633         3287           18  POPLATEK MESICNE          1        706213
816         2987           18  POPLATEK MESICNE          1        706213
884         2479           18  POPLATEK MESICNE          1        706213
1037        3003           18  POPLATEK MESICNE          1        706213
...          ...          ...               ...        ...           ...
4299         129           74  POPLATEK MESICNE      13998        535812
4404        2721           74  POPLATEK MESICNE      13998        535812
4428        3715           74  POPLATEK MESICNE      13998        535812
4486        4332           74  POPLATEK MESICNE      13998        535812
4491        3048           74    POPLATEK TYDNE      13998        535812

[648561 rows x 5 columns]

### Inner join on an index

In [76]:
dt_account.join(dt_client.set_index("district_id"), on="district_id", how="inner")

      account_id  district_id         frequency  client_id  birth_number
0            576           55  POPLATEK MESICNE        118        220719
0            576           55  POPLATEK MESICNE        119        225228
0            576           55  POPLATEK MESICNE        136        215126
0            576           55  POPLATEK MESICNE        145        780214
0            576           55  POPLATEK MESICNE        149        480627
...          ...          ...               ...        ...           ...
4360        2152           22  POPLATEK MESICNE       4766        670527
4360        2152           22  POPLATEK MESICNE       4769        235123
4360        2152           22  POPLATEK MESICNE       4770        241213
4360        2152           22  POPLATEK MESICNE      12468        690704
4360        2152           22  POPLATEK MESICNE      12756        495121

[648561 rows x 5 columns]

### Outer join on an index

In [77]:
dt_account.join(dt_client.set_index("district_id"), on="district_id", how="outer")

      account_id  district_id         frequency  client_id  birth_number
0            576           55  POPLATEK MESICNE        118        220719
0            576           55  POPLATEK MESICNE        119        225228
0            576           55  POPLATEK MESICNE        136        215126
0            576           55  POPLATEK MESICNE        145        780214
0            576           55  POPLATEK MESICNE        149        480627
...          ...          ...               ...        ...           ...
4360        2152           22  POPLATEK MESICNE       4766        670527
4360        2152           22  POPLATEK MESICNE       4769        235123
4360        2152           22  POPLATEK MESICNE       4770        241213
4360        2152           22  POPLATEK MESICNE      12468        690704
4360        2152           22  POPLATEK MESICNE      12756        495121

[648561 rows x 5 columns]

### Cross Join

In [78]:

dt_account.join(dt_client, how="cross", lsuffix="_1", rsuffix="_2")

,account_id,district_id_1,frequency,client_id,birth_number,district_id_2
0,576,55,POPLATEK MESICNE,1,706213,18
1,576,55,POPLATEK MESICNE,2,450204,1
2,576,55,POPLATEK MESICNE,3,406009,1
3,576,55,POPLATEK MESICNE,4,561201,5
4,576,55,POPLATEK MESICNE,5,605703,5
...,...,...,...,...,...,...
24160495,3276,1,POPLATEK MESICNE,13955,456030,1
24160496,3276,1,POPLATEK MESICNE,13956,430406,1
24160497,3276,1,POPLATEK MESICNE,13968,680413,61
24160498,3276,1,POPLATEK MESICNE,13971,626019,67
24160499,3276,1,POPLATEK MESICNE,13998,535812,74

## 1.3 - References

- https://jakevdp.github.io/PythonDataScienceHandbook/
- https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html

- https://geekpython.in/multiple-datasets-integration-using-pandas